version: "2"
services:
  mysql-db:
    image: percona
    environment:
     - MYSQL_ROOT_PASSWORD=1q2w3e4r5t
     - LANG=en_US.UTF-8
    volumes:
     - ./ext/mysql.conf.d:/etc/mysql/conf.d:ro
     - ./tmp:/var/lib/mysql
     - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    tmpfs:
     - /tmp
    mem_limit: 256m
    ports:
     - 3320:3306